### ISSUE TITLE
Compatibility with other UI helper module

### ISSUE THREAD

**Issue by AlexandreTexier** [jploch/AdminThemeCanvas#1]
Not a real "issue", but it would be nice, if possible, to have AdminThemeCanvas working with the small helper visible [here](https://github.com/eprcstudio/TagsToFolders).

For know if both modules are installed, it make somme parts of the UI vanish.

**Comment by jploch** [comment]
Can you please try the new version (v0.62). It should fix the issue.
There was a bug with more than 2 level dropdown navigation for some menues.
Now it should support any number of levels :)
